packages:
  - 'packages/*'
  - 'apps/*'
  - 'frontend'
  - 'tools/*'
catalog:
  type-fest: '^5.8.0'
catalogs:
  types:
    type-fest: '^5.8.0'
    "@types/passport-jwt": '^4.0.1'
  drivers:
    "pg": "^8.22.0"
    "mongoose": "^9.7.4"
    "ioredis": "^5.11.1"
    "amqp-connection-manager": "5.0.0"
    "amqplib": "2.0.1"
  backend:
    "cookie-parser": "^1.4.7"
    "typeorm": "^1.1.0"
    "express": "5.2.1"
    "@grpc/grpc-js": "^1.14.4"
    "passport-jwt": "^4.0.1"
  general:
    "@humanwhocodes/env": "^4.0.1"
    "effect": "^3.14.0"
    "tslib": "^2.8.1"
    "radash": "^12.1.1"
    "reflect-metadata": "0.2.2"
    "rxjs": "^7.8.2"
    "axios": "^1.18.1"
  validation:
    "class-validator": "^0.15.1"
    "class-transformer": "^0.5.1"
    "zod": "^4.4.3"
  nestjs:
    "nestjs-s3": "3.0.1"
    "@nestjs/passport": "11.0.5"
    "@nestjs/testing": "^11.1.28"
    "@nestjs/schematics": "^11.1.0"
    "@nestjs/bullmq": "^11.0.4"
    "@nestjs/common": "^11.1.28"
    "@nestjs/config": "^4.0.4"
    "@nestjs/core": "^11.1.28"
    "@nestjs/cqrs": "^11.0.3"
    "@nestjs/jwt": "^11.0.2"
    "@nestjs/microservices": "^11.1.28"
    "@nestjs/mongoose": "^11.0.4"
    "@nestjs/platform-express": "^11.1.28"
    "@nestjs/platform-ws": "^11.1.28"
    "@nestjs/swagger": "^11.4.5"
    "@nestjs/typeorm": "^11.0.3"
    "@nestjs/websockets": "^11.1.28"
    "rxjs": "^7.8.2"
  react:
    "react": "^19.2.7"
    "react-dom": "^19.2.7"
    "@mantine/core": "^9.4.1"
    "@mantine/dates": "^9.4.1"
    "@mantine/hooks": "^9.4.1"
    "@mantine/modals": "^9.4.1"
    "@mantine/notifications": "^9.4.1"
    "@mantine/spotlight": "^9.4.1"
    "@mantine/tiptap": "^9.4.1"
    "@phosphor-icons/react": "^2.1.10"
    "@tanstack/react-router": "^1.170.16"
    "@tanstack/react-query": "^5.101.2"
  yjs:
    "@hocuspocus/extension-redis": "^4.4.0"
    "@hocuspocus/provider": "^4.3.0"
    "y-protocols": "^1.0.7"
    "react-yjs": "^2.0.1"
    "y-websocket": "^1.5.4"
    "yjs": "13.6.31"
  swc:
    "@swc/helpers": "0.5.18"
  aws:
    "@aws-sdk/client-s3": "3.1075.0"
    "@aws-sdk/s3-request-presigner": "3.1075.0"
hoist: false
