services:
  clarte-frontend:
    image: apps-frontend:latest
    container_name: clarte-frontend
    ports:
      - '80:80'
    build:
      context: ../..
      dockerfile: apps/frontend/Dockerfile
    env_file:
      - .env
      - .env.docker
    networks:
      - default
networks:
  default:
    external: true
    name: clarte-network
