services:
  minio:
    image: minio/minio
    profiles:
      - minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: rootuser
      MINIO_ROOT_PASSWORD: superpassword
  postgres:
    profiles:
      - db
    image: postgres:16-alpine
    container_name: clarte-notes-service-postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
volumes:
  postgres_data:
  minio_data:
networks:
  default:
    name: clarte-network
