/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as AuthenticatedDRouteImport } from './routes/_authenticated/d';

const AuthenticatedDRoute = AuthenticatedDRouteImport.update({
  id: '/_authenticated/d',
  path: '/d',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/d': typeof AuthenticatedDRoute;
}
export interface FileRoutesByTo {
  '/d': typeof AuthenticatedDRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_authenticated/d': typeof AuthenticatedDRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/d';
  fileRoutesByTo: FileRoutesByTo;
  to: '/d';
  id: '__root__' | '/_authenticated/d';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthenticatedDRoute: typeof AuthenticatedDRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/d': {
      id: '/_authenticated/d';
      path: '/d';
      fullPath: '/d';
      preLoaderRoute: typeof AuthenticatedDRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedDRoute: AuthenticatedDRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
