// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty } from "./google/protobuf/empty";

export const protobufPackage = "user";

export interface UserFindByIdRequest {
  id: string;
}

export interface UserCreateRequest {
  id: string;
  login: string;
  passwordHash: string;
}

export interface UserFindByLoginResponse {
  id: string;
  login: string;
  avatarUrl: string;
}

export interface UserFindByIdResponse {
  id: string;
  login: string;
  avatarUrl: string;
}

export interface UserFindByLoginRequest {
  login: string;
}

export interface UserGetCredentialsByLoginRequest {
  login: string;
}

export interface UserGetCredentialsByLoginResponse {
  id: string;
  login: string;
  passwordHash: string;
}

export const USER_PACKAGE_NAME = "user";

export interface UserCreateServiceClient {
  userCreate(request: UserCreateRequest): Observable<Empty>;
}

export interface UserCreateServiceController {
  userCreate(request: UserCreateRequest): void | Promise<void>;
}

export function UserCreateServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["userCreate"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserCreateService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserCreateService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_CREATE_SERVICE_NAME = "UserCreateService";

export interface UserFindServiceClient {
  findById(request: UserFindByIdRequest): Observable<UserFindByIdResponse>;

  findByLogin(request: UserFindByLoginRequest): Observable<UserFindByLoginResponse>;
}

export interface UserFindServiceController {
  findById(
    request: UserFindByIdRequest,
  ): Promise<UserFindByIdResponse> | Observable<UserFindByIdResponse> | UserFindByIdResponse;

  findByLogin(
    request: UserFindByLoginRequest,
  ): Promise<UserFindByLoginResponse> | Observable<UserFindByLoginResponse> | UserFindByLoginResponse;
}

export function UserFindServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["findById", "findByLogin"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserFindService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserFindService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_FIND_SERVICE_NAME = "UserFindService";

export interface UserCredentialsServiceClient {
  getCredentialsByLogin(request: UserGetCredentialsByLoginRequest): Observable<UserGetCredentialsByLoginResponse>;
}

export interface UserCredentialsServiceController {
  getCredentialsByLogin(
    request: UserGetCredentialsByLoginRequest,
  ):
    | Promise<UserGetCredentialsByLoginResponse>
    | Observable<UserGetCredentialsByLoginResponse>
    | UserGetCredentialsByLoginResponse;
}

export function UserCredentialsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getCredentialsByLogin"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserCredentialsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserCredentialsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_CREDENTIALS_SERVICE_NAME = "UserCredentialsService";
