// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.9
//   protoc               v7.34.0
// source: auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty } from "./google/protobuf/empty";

export const protobufPackage = "auth";

export interface GetPublicJwtKeyResponse {
  key: string;
}

export interface LoginPasswordRequest {
  login: string;
  password: string;
  userAgent: string;
}

export interface LoginPasswordResponse {
  success: boolean;
  refreshToken: string;
  accessToken: string;
  userId: string;
}

export interface ValidateUserRequest {
  login: string;
  password: string;
}

export interface ValidateUserResponse {
  id: string;
  login: string;
}

export interface RegisterRequest {
  login: string;
  password: string;
}

export interface RefreshTokensRequest {
  userId: string;
  refreshToken: string;
}

export interface RefreshTokensResponse {
  accessToken: string;
  refreshToken: string;
}

export const AUTH_PACKAGE_NAME = "auth";

export interface AuthServiceClient {
  validateUser(request: ValidateUserRequest): Observable<ValidateUserResponse>;

  loginPassword(request: LoginPasswordRequest): Observable<LoginPasswordResponse>;

  registerPassword(request: RegisterRequest): Observable<Empty>;

  getPublicJwtKey(request: Empty): Observable<GetPublicJwtKeyResponse>;

  refreshTokens(request: RefreshTokensRequest): Observable<RefreshTokensResponse>;
}

export interface AuthServiceController {
  validateUser(
    request: ValidateUserRequest,
  ): Promise<ValidateUserResponse> | Observable<ValidateUserResponse> | ValidateUserResponse;

  loginPassword(
    request: LoginPasswordRequest,
  ): Promise<LoginPasswordResponse> | Observable<LoginPasswordResponse> | LoginPasswordResponse;

  registerPassword(request: RegisterRequest): void | Promise<void>;

  getPublicJwtKey(
    request: Empty,
  ): Promise<GetPublicJwtKeyResponse> | Observable<GetPublicJwtKeyResponse> | GetPublicJwtKeyResponse;

  refreshTokens(
    request: RefreshTokensRequest,
  ): Promise<RefreshTokensResponse> | Observable<RefreshTokensResponse> | RefreshTokensResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "validateUser",
      "loginPassword",
      "registerPassword",
      "getPublicJwtKey",
      "refreshTokens",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
