// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.35.1
// source: notes.proto

/* eslint-disable */
import type { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';
import { Empty } from './google/protobuf/empty.js';

export const protobufPackage = 'notes';

export interface CreateNoteResponse {
  id: string;
}

export interface AccessCheckRequest {
  noteId: string;
}

export interface AccessCheckResponse {
  status: boolean;
}

export interface Note {
  id: string;
  label: string;
  content?: string | undefined;
  tags: string[];
  parentId?: string | undefined;
  linksTo: string[];
  type: string;
  authorId: string;
  createdAt: string;
  updatedAt: string;
  bytes?: Uint8Array | undefined;
}

export interface GetNoteByIdRequest {
  id: string;
}

export interface GetBytesRequest {
  id: string;
}

export interface GetBytesResponse {
  bytes: Uint8Array;
}

export interface CreateNoteRequest {
  label: string;
  content?: string | undefined;
  tags: string[];
  bytes?: Uint8Array | undefined;
  parentId?: string | undefined;
  linksTo: string[];
  type?: string | undefined;
}

export interface SaveNoteBytesRequest {
  id: string;
  bytes: Uint8Array;
  content?: string | undefined;
}

export interface GetAllUserNotesResponse {
  notes: Note[];
}

export const NOTES_PACKAGE_NAME = 'notes';

export interface NotesServiceClient {
  createNote(request: CreateNoteRequest, metadata?: Metadata): Observable<CreateNoteResponse>;

  getBytes(request: GetBytesRequest, metadata?: Metadata): Observable<GetBytesResponse>;

  getNoteById(request: GetNoteByIdRequest, metadata?: Metadata): Observable<Note>;

  saveNoteBytes(request: SaveNoteBytesRequest, metadata?: Metadata): Observable<Empty>;

  accessCheck(request: AccessCheckRequest, metadata?: Metadata): Observable<AccessCheckResponse>;

  getAllUserNotes(request: Empty, metadata?: Metadata): Observable<GetAllUserNotesResponse>;
}

export interface NotesServiceController {
  createNote(
    request: CreateNoteRequest,
    metadata?: Metadata,
  ): Promise<CreateNoteResponse> | Observable<CreateNoteResponse> | CreateNoteResponse;

  getBytes(
    request: GetBytesRequest,
    metadata?: Metadata,
  ): Promise<GetBytesResponse> | Observable<GetBytesResponse> | GetBytesResponse;

  getNoteById(
    request: GetNoteByIdRequest,
    metadata?: Metadata,
  ): Promise<Note> | Observable<Note> | Note;

  saveNoteBytes(request: SaveNoteBytesRequest, metadata?: Metadata): void | Promise<void>;

  accessCheck(
    request: AccessCheckRequest,
    metadata?: Metadata,
  ): Promise<AccessCheckResponse> | Observable<AccessCheckResponse> | AccessCheckResponse;

  getAllUserNotes(
    request: Empty,
    metadata?: Metadata,
  ):
    | Promise<GetAllUserNotesResponse>
    | Observable<GetAllUserNotesResponse>
    | GetAllUserNotesResponse;
}

export function NotesServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'createNote',
      'getBytes',
      'getNoteById',
      'saveNoteBytes',
      'accessCheck',
      'getAllUserNotes',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('NotesService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('NotesService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const NOTES_SERVICE_NAME = 'NotesService';
