// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.35.1
// source: notification.proto

/* eslint-disable */
import type { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';
import { Empty } from './google/protobuf/empty.js';

export const protobufPackage = 'notification';

export interface Notification {
  id: string;
  title: string;
  text: string;
  createdAt: string;
}

export interface GetNotificationsByIdResponse {
  notifications: Notification[];
}

export const NOTIFICATION_PACKAGE_NAME = 'notification';

export interface NotificationServiceClient {
  getNotificationsById(
    request: Empty,
    metadata?: Metadata,
  ): Observable<GetNotificationsByIdResponse>;
}

export interface NotificationServiceController {
  getNotificationsById(
    request: Empty,
    metadata?: Metadata,
  ):
    | Promise<GetNotificationsByIdResponse>
    | Observable<GetNotificationsByIdResponse>
    | GetNotificationsByIdResponse;
}

export function NotificationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['getNotificationsById'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('NotificationService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('NotificationService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const NOTIFICATION_SERVICE_NAME = 'NotificationService';
