// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.0
// source: notification.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "notification";

export interface Notification {
  id: string;
  title: string;
  text: string;
  createdAt: string;
}

export interface GetNotificationsByIdRequest {
  userId: string;
}

export interface GetNotificationsByIdResponse {
  notifications: Notification[];
}

export const NOTIFICATION_PACKAGE_NAME = "notification";

export interface NotificationServiceClient {
  getNotificationsById(request: GetNotificationsByIdRequest): Observable<GetNotificationsByIdResponse>;
}

export interface NotificationServiceController {
  getNotificationsById(
    request: GetNotificationsByIdRequest,
  ): Promise<GetNotificationsByIdResponse> | Observable<GetNotificationsByIdResponse> | GetNotificationsByIdResponse;
}

export function NotificationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getNotificationsById"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("NotificationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("NotificationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const NOTIFICATION_SERVICE_NAME = "NotificationService";
