// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.35.1
// source: todo.proto

/* eslint-disable */
import type { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';
import { Empty } from './google/protobuf/empty.js';

export const protobufPackage = 'todo';

export interface TodoResponse {
  id: string;
  userId: string;
  title: string;
  description: string;
  isCompleted: boolean;
  dueDate: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateTodoRequest {
  title: string;
  description: string;
  dueDate: string;
}

export interface CreateTodoResponse {
  id: string;
}

export interface UpdateTodoRequest {
  id: string;
  title?: string | undefined;
  description?: string | undefined;
  dueDate?: string | undefined;
  isCompleted?: boolean | undefined;
}

export interface CompleteTodoRequest {
  id: string;
}

export interface UncompleteTodoRequest {
  id: string;
}

export interface DeleteTodoRequest {
  id: string;
}

export interface GetUserTodsResponse {
  todos: TodoResponse[];
}

export const TODO_PACKAGE_NAME = 'todo';

export interface TodoServiceClient {
  createTodo(request: CreateTodoRequest, metadata?: Metadata): Observable<CreateTodoResponse>;

  updateTodo(request: UpdateTodoRequest, metadata?: Metadata): Observable<Empty>;

  getUserTodos(request: Empty, metadata?: Metadata): Observable<GetUserTodsResponse>;

  completeTodo(request: CompleteTodoRequest, metadata?: Metadata): Observable<Empty>;

  uncompleteTodo(request: UncompleteTodoRequest, metadata?: Metadata): Observable<Empty>;

  deleteTodo(request: DeleteTodoRequest, metadata?: Metadata): Observable<Empty>;
}

export interface TodoServiceController {
  createTodo(
    request: CreateTodoRequest,
    metadata?: Metadata,
  ): Promise<CreateTodoResponse> | Observable<CreateTodoResponse> | CreateTodoResponse;

  updateTodo(request: UpdateTodoRequest, metadata?: Metadata): void | Promise<void>;

  getUserTodos(
    request: Empty,
    metadata?: Metadata,
  ): Promise<GetUserTodsResponse> | Observable<GetUserTodsResponse> | GetUserTodsResponse;

  completeTodo(request: CompleteTodoRequest, metadata?: Metadata): void | Promise<void>;

  uncompleteTodo(request: UncompleteTodoRequest, metadata?: Metadata): void | Promise<void>;

  deleteTodo(request: DeleteTodoRequest, metadata?: Metadata): void | Promise<void>;
}

export function TodoServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'createTodo',
      'updateTodo',
      'getUserTodos',
      'completeTodo',
      'uncompleteTodo',
      'deleteTodo',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('TodoService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('TodoService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TODO_SERVICE_NAME = 'TodoService';
