// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: todo.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty } from "./google/protobuf/empty";

export const protobufPackage = "todo";

export interface TodoResponse {
  id: string;
  userId: string;
  title: string;
  description: string;
  isCompleted: boolean;
  dueDate: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateTodoRequest {
  title: string;
  description: string;
  dueDate: string;
  userId: string;
}

export interface CreateTodoResponse {
  id: string;
}

export interface UpdateTodoRequest {
  id: string;
  userId: string;
  title?: string | undefined;
  description?: string | undefined;
  dueDate?: string | undefined;
  isCompleted?: boolean | undefined;
}

export interface GetUserTodosRequest {
  id: string;
  userId: string;
}

export interface GetUserTodsResponse {
  todos: TodoResponse[];
}

export const TODO_PACKAGE_NAME = "todo";

export interface TodoServiceClient {
  createTodo(request: CreateTodoRequest): Observable<CreateTodoResponse>;

  updateTodo(request: UpdateTodoRequest): Observable<Empty>;

  getUserTodos(request: GetUserTodosRequest): Observable<GetUserTodsResponse>;
}

export interface TodoServiceController {
  createTodo(
    request: CreateTodoRequest,
  ): Promise<CreateTodoResponse> | Observable<CreateTodoResponse> | CreateTodoResponse;

  updateTodo(request: UpdateTodoRequest): void | Promise<void>;

  getUserTodos(
    request: GetUserTodosRequest,
  ): Promise<GetUserTodsResponse> | Observable<GetUserTodsResponse> | GetUserTodsResponse;
}

export function TodoServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createTodo", "updateTodo", "getUserTodos"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("TodoService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("TodoService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TODO_SERVICE_NAME = "TodoService";
