// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user";

export interface UserFindByIdRequest {
  id: string;
}

export interface User {
  id: string;
  login: string;
  avatarUrl: string;
}

export interface UserFindByLoginRequest {
  login: string;
}

export interface UserGetCredentialsByIdRequest {
  id: string;
}

export interface UserGetCredentialsByIdResponse {
  passwordHash: string;
}

export const USER_PACKAGE_NAME = "user";

export interface UserFindServiceClient {
  findById(request: UserFindByIdRequest): Observable<User>;

  findByLogin(request: UserFindByLoginRequest): Observable<User>;
}

export interface UserFindServiceController {
  findById(request: UserFindByIdRequest): Promise<User> | Observable<User> | User;

  findByLogin(request: UserFindByLoginRequest): Promise<User> | Observable<User> | User;
}

export function UserFindServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["findById", "findByLogin"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserFindService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserFindService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_FIND_SERVICE_NAME = "UserFindService";

export interface UserCredentialsServiceClient {
  getCredentialsById(request: UserGetCredentialsByIdRequest): Observable<UserGetCredentialsByIdResponse>;
}

export interface UserCredentialsServiceController {
  getCredentialsById(
    request: UserGetCredentialsByIdRequest,
  ):
    | Promise<UserGetCredentialsByIdResponse>
    | Observable<UserGetCredentialsByIdResponse>
    | UserGetCredentialsByIdResponse;
}

export function UserCredentialsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getCredentialsById"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserCredentialsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserCredentialsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_CREDENTIALS_SERVICE_NAME = "UserCredentialsService";
