include:
  - compose.infra.yml
services:
  clarte-notification-service:
    extends:
      file: compose.microservice.yml
      service: clarte-notification-service
    depends_on:
      - clarte-notification-service-postgres
