name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      - run: npx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # Get pnpm store directory
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      # Setup pnpm cache
      - uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles("**/pnpm-lock.yaml") }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # Install dependencies with pnpm
      - run: pnpm install --frozen-lockfile

      # Prepend any command with "nx record --" to record its logs to Nx Cloud
      - run: npx nx record -- npx nx format:check  --base="remotes/origin/main"
      - run: npx nx run-many -t lint test build typecheck e2e-ci
      # Nx Cloud recommends fixes for failures to help you get CI green faster.
      - run: npx nx fix-ci
        if: always()
